spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3308/pass_local?zeroDateTimeBehavior=convertToNull&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: pass_local_user
    password: passlocal123
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
  batch:
    job:
      name: ${job.name:NONE} #job name을 파라미터로 받기 위함
      enabled: true

kakaotalk:
  host: https://kapi.kakao.com
  token: 466678c82f31549a40ee144a6f962960

logging:
  level:
    org.springframework.batch: DEBUG
